### ISSUE TITLE
Unable to host MongoDB behind nginx proxy_pass server

### ISSUE THREAD

**Issue by danieldonaldson** [huggingface/Mongoku#17]
As per the topic, I'm trying to host Mongoku on a webserver, and need some kind of password protection. I am unable to proxy_pass it with Nginx as it seems Mongoku passes to root. I've tried to rewrite to no avail. Any solutions?

Edit, my nginx code is as follows:
`location /mongoku/ {
    rewrite ^/mongoku/?(.*)$ /$1 break;
    proxy_pass  http://127.0.0.1:3100;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}`

**Comment by n1t0** [comment]
Hi @danieldonaldson, this is happening because you are prefixing the base url with `/mongoku`.

Can you try using the last version available on `master`, building with the `Manual build` method described in the `README`? Instead of the `ng build` step, use the following: `ng build --prod --baseHref=/mongoku/` and it should fix your problem. 

If you don't want to use this method, you will need to have a `location / {` in nginx, without the `rewrite` clause.

**Comment by n1t0** [comment]
Closing this. Please reopen if needed
