### ISSUE TITLE
Querying - how?

### ISSUE THREAD

**Issue by StewAlexander-com** [huggingface/Mongoku#57]
I'm trying to figure out the query syntax, if there is any...

Anyone else cracked this? 

Please let me know thanks

**Comment by julien-c** [comment]
Check out [MongoDB's doc](https://docs.mongodb.com/manual/tutorial/query-documents/)

**Comment by StewAlexander-com** [comment]
I tried, says error... I'm doing something wrong, but what?

![image](https://user-images.githubusercontent.com/48565067/107787471-1e042780-6d1d-11eb-9612-608ee1a48ae8.png)

**Comment by julien-c** [comment]
Try `{inet: "foobar"}`

**Comment by StewAlexander-com** [comment]
We;; that gave me nothing, should I use the word "foobar"?

At least it didn't error out

Here's how my data is formatted:
![image](https://user-images.githubusercontent.com/48565067/107799435-662a4680-6d2b-11eb-84cd-f00a0c239aa8.png)

**Comment by n1t0** [comment]
@StewAlexander-com The query should be exactly what you give to `db.network.find()`. For more information about how to build a MongoDB query, you'll have to check the [MongoDB's doc](https://docs.mongodb.com/manual/tutorial/query-documents/) though.

In your case it probably gave you nothing because you probably don't have a field `inet` that contains `foobar`.

**Comment by StewAlexander-com** [comment]
Now a defunct issue, closing
